// Neo Plugin SDK
// TypeScript SDK for building Neo plugins

// Re-export types from bindings (generated by ts-rs)
export type { PointValue } from "../../../bindings/bindings/PointValue.ts";
export type { ServiceRequest } from "../../../bindings/bindings/ServiceRequest.ts";
export type { ServiceResponse } from "../../../bindings/bindings/ServiceResponse.ts";
export type { Alarm } from "../../../bindings/bindings/Alarm.ts";
export type { AlarmState } from "../../../bindings/bindings/AlarmState.ts";
export type { Schedule } from "../../../bindings/bindings/Schedule.ts";
export type { ScheduleEntry } from "../../../bindings/bindings/ScheduleEntry.ts";
export type { ScheduleException } from "../../../bindings/bindings/ScheduleException.ts";
export type { HistorySample } from "../../../bindings/bindings/HistorySample.ts";
export type { PointQuality } from "../../../bindings/bindings/PointQuality.ts";
export type { AlarmSeverity } from "../../../bindings/bindings/AlarmSeverity.ts";
export type { ServiceState } from "../../../bindings/bindings/ServiceState.ts";
export type { Weekday } from "../../../bindings/bindings/Weekday.ts";
export type { JsonValue } from "../../../bindings/serde_json/JsonValue.ts";

import type { PointValue } from "../../../bindings/bindings/PointValue.ts";
import type { ServiceRequest } from "../../../bindings/bindings/ServiceRequest.ts";
import type { ServiceResponse } from "../../../bindings/bindings/ServiceResponse.ts";
import type { JsonValue } from "../../../bindings/serde_json/JsonValue.ts";

// -----------------------------------------------------------------------------
// Neo Global Type Declaration
// -----------------------------------------------------------------------------

/**
 * Event published to the Neo event bus
 */
export interface NeoEvent {
    /** Event type identifier */
    type: string;
    /** Source of the event (e.g., plugin ID, device path) */
    source?: string;
    /** ISO 8601 timestamp */
    timestamp?: string;
    /** Event-specific data */
    data?: unknown;
}

/**
 * The Neo global object provided by the runtime
 */
export interface NeoGlobal {
    /** Plugin's unique identifier */
    readonly pluginId: string;

    /** Plugin configuration from neo-plugin.json */
    readonly config: Record<string, unknown>;

    /** Point read/write operations */
    points: {
        /**
         * Read a point value
         * @param path - Point path like "network/device/AI:1" or "virtual/weather/temp"
         * @returns Promise resolving to the point value
         */
        read(path: string): Promise<PointValue>;

        /**
         * Write a point value
         * @param path - Point path
         * @param value - Value to write (e.g., { Real: 72.5 } or { Boolean: true })
         */
        write(path: string, value: PointValue): void;
    };

    /** Event operations */
    events: {
        /**
         * Publish an event to the Neo event bus
         * @param event - Event to publish
         */
        publish(event: NeoEvent): void;
    };

    /** Logging utilities */
    log: {
        trace(msg: string): void;
        debug(msg: string): void;
        info(msg: string): void;
        warn(msg: string): void;
        error(msg: string): void;
    };

    /** Time utilities */
    time: {
        /** Get current timestamp in milliseconds since Unix epoch */
        now(): number;
    };
}

/**
 * Service plugin interface - implement this to create a plugin
 */
export interface ServicePlugin {
    /** Called when the service starts */
    onStart?(): Promise<void>;

    /** Called when the service stops */
    onStop?(): Promise<void>;

    /** Called when a subscribed event is received */
    onEvent?(event: NeoEvent): Promise<void>;

    /** Called to handle a service request */
    onRequest?(request: ServiceRequest): Promise<ServiceResponse>;
}

// Declare the global Neo object
declare global {
    const Neo: NeoGlobal;
    function __neo_register_plugin(plugin: ServicePlugin): void;
    function defineService(plugin: ServicePlugin): void;
}

// -----------------------------------------------------------------------------
// Helper Functions
// -----------------------------------------------------------------------------

/**
 * Define and register a Neo service plugin
 * @param plugin - Plugin implementation
 */
export function defineService(plugin: ServicePlugin): void {
    __neo_register_plugin(plugin);
}

/**
 * Get the plugin configuration with proper typing
 * @returns Typed configuration object
 */
export function getConfig<T>(): T {
    return Neo.config as T;
}

/**
 * Create a Real point value
 */
export function real(value: number): PointValue {
    return { Real: value };
}

/**
 * Create an Unsigned point value
 */
export function unsigned(value: number): PointValue {
    return { Unsigned: value };
}

/**
 * Create a Boolean point value
 */
export function boolean(value: boolean): PointValue {
    return { Boolean: value };
}

/**
 * Create an Enumerated point value
 */
export function enumerated(value: number): PointValue {
    return { Enumerated: value };
}

/**
 * Create a Null point value
 */
export function nullValue(): PointValue {
    return "Null";
}

/**
 * Extract a number from a PointValue (Real or Unsigned)
 * @returns The numeric value, or undefined if not a numeric type
 */
export function asNumber(value: PointValue): number | undefined {
    if (typeof value === "object" && value !== null) {
        if ("Real" in value) return value.Real;
        if ("Unsigned" in value) return value.Unsigned;
        if ("Enumerated" in value) return value.Enumerated;
    }
    return undefined;
}

/**
 * Extract a boolean from a PointValue
 * @returns The boolean value, or undefined if not a boolean type
 */
export function asBoolean(value: PointValue): boolean | undefined {
    if (typeof value === "object" && value !== null && "Boolean" in value) {
        return value.Boolean;
    }
    return undefined;
}

/**
 * Check if a PointValue is Null
 */
export function isNull(value: PointValue): boolean {
    return value === "Null";
}

// -----------------------------------------------------------------------------
// Response Helpers
// -----------------------------------------------------------------------------

/**
 * Create an OK response
 */
export function okResponse(): ServiceResponse {
    return { type: "Ok" };
}

/**
 * Create an error response
 */
export function errorResponse(code: string, message: string): ServiceResponse {
    return { type: "Error", code, message };
}

/**
 * Create a custom response with payload
 */
export function customResponse(payload: JsonValue): ServiceResponse {
    return { type: "Custom", payload };
}
