// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alarm lifecycle state
 */
export type AlarmState = "Active" | "Acknowledged" | "Cleared";
