// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlarmSeverity } from "./AlarmSeverity";
import type { AlarmState } from "./AlarmState";
import type { PointValue } from "./PointValue";

/**
 * An alarm instance
 */
export type Alarm = { id: string, source: string, message: string, severity: AlarmSeverity, state: AlarmState, triggered_at: string, acknowledged_at: string | null, acknowledged_by: string | null, cleared_at: string | null, value_at_trigger: PointValue | null, };
