// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointQuality } from "./PointQuality";
import type { PointValue } from "./PointValue";

/**
 * A single historical data sample
 */
export type HistorySample = { timestamp: string, value: PointValue, quality: PointQuality, };
