// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point quality indicator
 */
export type PointQuality = "Good" | "Bad" | "Uncertain" | "Stale";
