// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointValue } from "./PointValue";
import type { Weekday } from "./Weekday";

/**
 * A single schedule entry (time + value)
 */
export type ScheduleEntry = { days: Array<Weekday>, 
/**
 * Time in HH:MM:SS format
 */
time: string, value: PointValue, };
