// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { Schedule } from "./Schedule";

/**
 * Request types that can be sent to any service
 */
export type ServiceRequest = { "type": "GetStatus" } | { "type": "GetConfig" } | { "type": "SetConfig", config: JsonValue, } | { "type": "QueryHistory", point: string, start: string, end: string, limit: number | null, } | { "type": "GetActiveAlarms" } | { "type": "AcknowledgeAlarm", alarm_id: string, comment: string | null, } | { "type": "GetAlarmHistory", start: string, end: string, source_filter: string | null, } | { "type": "GetSchedules" } | { "type": "CreateSchedule", schedule: Schedule, } | { "type": "UpdateSchedule", id: string, schedule: Schedule, } | { "type": "DeleteSchedule", id: string, } | { "type": "Custom", action: string, payload: JsonValue, };
