// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alarm rule
 */
export type AlarmRule = { id: string, name: string, condition: string, priority: string, enabled: boolean, message: string | null, };
