// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlarmRule } from "./AlarmRule";

/**
 * Alarm rule configuration (alarms/rules.toml)
 */
export type AlarmRulesConfig = { rules: Array<AlarmRule>, };
