// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Blueprint configuration (blueprints/*.bp.json)
 */
export type BlueprintConfig = { id: string, name: string, description: string | null, nodes: Array<JsonValue>, connections: Array<JsonValue>, metadata: JsonValue, };
