// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { PluginRegistration } from "./PluginRegistration";

/**
 * Messages sent from client to server
 */
export type ClientMessage = { "type": "Subscribe", 
/**
 * Request ID for correlation
 */
id: string, 
/**
 * Paths to subscribe to (supports wildcards)
 */
paths: Array<string>, } | { "type": "Unsubscribe", id: string, paths: Array<string>, } | { "type": "Get", id: string, path: string, } | { "type": "Update", id: string, path: string, data: JsonValue, } | { "type": "Create", id: string, path: string, data: JsonValue, } | { "type": "Delete", id: string, path: string, } | { "type": "Ping", id: string, } | { "type": "plugin:register", plugin: PluginRegistration, } | { "type": "plugin:rebuilt", pluginId: string, entryPath: string, };
