// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection configuration
 */
export type ConnectionConfig = { protocol: string, address: string | null, device_id: number | null, port: number | null, };
