// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * Day schedule
 */
export type DaySchedule = { occupied: Array<TimeRange>, };
