// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionConfig } from "./ConnectionConfig";
import type { DeviceInfo } from "./DeviceInfo";
import type { PointConfig } from "./PointConfig";

/**
 * Device configuration (devices/*.device.toml)
 */
export type DeviceConfig = { device: DeviceInfo, connection: ConnectionConfig, points: Array<PointConfig>, };
