// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocationConfig } from "./LocationConfig";

/**
 * Device information
 */
export type DeviceInfo = { id: string, name: string, type: string, description: string | null, manufacturer: string | null, model: string | null, location: LocationConfig, };
