// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error codes
 */
export type ErrorCode = "INVALID_REQUEST" | "INVALID_PATH" | "NOT_FOUND" | "ALREADY_EXISTS" | "UNAUTHORIZED" | "INTERNAL_ERROR";
