// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device location
 */
export type LocationConfig = { building: string | null, floor: string | null, zone: string | null, room: string | null, };
