// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node entry in the plugin manifest
 */
export type NodeEntry = { 
/**
 * Full node ID (plugin-id/node-name)
 */
id: string, 
/**
 * Path to the built chunk relative to dist
 */
entry: string, };
