// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Plugin registration data from Vite plugin
 */
export type PluginRegistration = { id: string, name: string, description: string | null, entryPath: string, subscriptions: Array<string>, tickInterval: bigint | null, config: JsonValue, };
