// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeEntry } from "./NodeEntry";
import type { ServiceEntry } from "./ServiceEntry";

/**
 * Plugin manifest (plugins/*/neo-plugin.json)
 * New declarative format with services and nodes arrays.
 */
export type PluginManifest = { 
/**
 * Unique plugin identifier
 */
id: string, 
/**
 * Human-readable name
 */
name: string, 
/**
 * Description
 */
description: string | null, 
/**
 * Services provided by this plugin
 */
services: Array<ServiceEntry>, 
/**
 * Blueprint nodes provided by this plugin
 */
nodes: Array<NodeEntry>, };
