// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point configuration
 */
export type PointConfig = { id: string, name: string, object_type: string, instance: number, unit: string | null, description: string | null, };
