// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectInfo } from "./ProjectInfo";
import type { RuntimeConfig } from "./RuntimeConfig";

/**
 * Project manifest (project.toml)
 */
export type ProjectManifest = { project: ProjectInfo, runtime: RuntimeConfig, };
