// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaySchedule } from "./DaySchedule";
import type { ScheduleInfo } from "./ScheduleInfo";
import type { ZoneOverride } from "./ZoneOverride";

/**
 * Schedule configuration (schedules/*.schedule.toml)
 */
export type ScheduleConfig = { schedule: ScheduleInfo, default_schedule: { [key in string]?: DaySchedule }, zone_overrides: { [key in string]?: ZoneOverride }, };
