// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";
import type { ErrorCode } from "./ErrorCode";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Messages sent from server to client
 */
export type ServerMessage = { "type": "Connected", session_id: string, server_version: string, } | { "type": "Response", id: string, success: boolean, data: JsonValue | null, error: string | null, } | { "type": "Change", path: string, change_type: ChangeType, data: JsonValue | null, } | { "type": "Error", id: string | null, code: ErrorCode, message: string, } | { "type": "Pong", id: string, } | { "type": "plugin:registered", pluginId: string, } | { "type": "plugin:restarted", pluginId: string, };
