// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A service entry in the plugin manifest
 */
export type ServiceEntry = { 
/**
 * Full service ID (plugin-id/service-name)
 */
id: string, 
/**
 * Path to the built chunk relative to dist
 */
entry: string, 
/**
 * Tick interval in milliseconds
 */
tickInterval: bigint | null, 
/**
 * Event subscriptions
 */
subscriptions: Array<string>, };
