// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaySchedule } from "./DaySchedule";

/**
 * Zone override
 */
export type ZoneOverride = { name: string, schedule: { [key in string]?: DaySchedule }, notes: string | null, };
