// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point value types
 */
export type PointValue = { "Real": number } | { "Unsigned": number } | { "Boolean": boolean } | { "Enumerated": number } | "Null";
