// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleEntry } from "./ScheduleEntry";
import type { ScheduleException } from "./ScheduleException";

/**
 * A schedule definition
 */
export type Schedule = { id: string | null, name: string, target_point: string, entries: Array<ScheduleEntry>, exceptions: Array<ScheduleException>, enabled: boolean, };
