// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduleEntry } from "./ScheduleEntry";

/**
 * An exception to the normal schedule (e.g., holidays)
 */
export type ScheduleException = { 
/**
 * Date in YYYY-MM-DD format
 */
date: string, name: string | null, entries: Array<ScheduleEntry>, };
