// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alarm } from "./Alarm";
import type { HistorySample } from "./HistorySample";
import type { JsonValue } from "../serde_json/JsonValue";
import type { Schedule } from "./Schedule";
import type { ServiceState } from "./ServiceState";

/**
 * Response types from services
 */
export type ServiceResponse = { "type": "Status", id: string, name: string, state: ServiceState, uptime_seconds: bigint, extra: JsonValue | null, } | { "type": "Config", config: JsonValue, } | { "type": "Ok" } | { "type": "HistoryData", samples: Array<HistorySample>, } | { "type": "ActiveAlarms", alarms: Array<Alarm>, } | { "type": "AlarmHistory", alarms: Array<Alarm>, } | { "type": "AlarmAcknowledged", alarm_id: string, } | { "type": "Schedules", schedules: Array<Schedule>, } | { "type": "ScheduleCreated", id: string, } | { "type": "ScheduleUpdated", id: string, } | { "type": "ScheduleDeleted", id: string, } | { "type": "Custom", payload: JsonValue, } | { "type": "Error", code: string, message: string, };
