// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service lifecycle states
 */
export type ServiceState = "Stopped" | "Starting" | "Running" | "Stopping" | "Failed";
